### ISSUE TITLE
invalid argument 0: Sizes of tensors must match except in dimension 0. Got 128 and 0 in dimension 2

### ISSUE THREAD

**Issue by qingfengmingyue** [xinntao/BasicSR#109]
19-04-22 20:35:30.702 - INFO: Start training from epoch: 0, iter: 0,total_epochs:4879
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    main()
  File "train.py", line 98, in main
    for step, train_data in enumerate(train_loader):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 229, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 229, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/root/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 209, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 128 and 0 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1307

**Comment by xinntao** [comment]
Check your data and the input.

**Comment by fayazdharejo** [comment]
I am facing same issue as well,  can you please explain more ?
