### ISSUE TITLE
HR and LR datasets have different number of images - 14, 56.

### ISSUE THREAD

**Issue by yaolugithub** [xinntao/BasicSR#130]
Hello,
   (1)Firstly, thank you for opening your code and it is extremely excellent work.  
   (2) When i trained the ESRGAN with python3.5,pytorch1.0,  i  have  generated DIV2K800_sub(HR) and DIV2K800_sub_bicLRx4 (LR) with extract_subimgs_single.py, but DIV2K800_sub_bicLRx4 only has 12 images.(?)

     Then i have generated   DIV2K800_sub.lmdb and  DIV2K800_sub_bicLRx4.lmdb with create_lmdb.py 

    My train_ESRGAN.json is 
"dataroot_HR": "/home/yaolu/dataset/DIV2K/DIV2K_train_HR/DIV2K800_sub.lmdb"

"dataroot_LR": "/home/yaolu/dataset/DIV2K/DIV2K_train_LR_bicubic/X4/DIV2K800_sub_bicLRx4.lmdb"

val": {
      "name": "val_set14_part"
      , "mode": "LRHR"
      , "dataroot_HR": "/home/yaolu/dataset/Set14"
      , "dataroot_LR": "/home/yaolu/dataset/Set14/LR_bicubic/X4"
    }
,which are modified with my situation.

(3)Next i trained the training code with   python train.py -opt options/train/train_ESRGAN.json
 i got the error as follows:
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main()
  File "train.py", line 74, in main
    val_set = create_dataset(dataset_opt)
  File "/home/ylu/ESRGAN-BasicSR/codes/data/__init__.py", line 33, in create_dataset
    dataset = D(dataset_opt)
  File "/home/ylu/ESRGAN-BasicSR/codes/data/LRHR_dataset.py", line 40, in __init__
    len(self.paths_LR), len(self.paths_HR))
AssertionError: HR and LR datasets have different number of images - 14, 56.

I have not idea about how to solve it .Can you give some suggestions ? thanks a lot.

**Comment by xinntao** [comment]
The error is from that the HR and LR folders have a different number of images. Check the folders. 

If you use `extract_subimgs_single.py` to extract LR images, you need to modify some configs.
Refer to #132

You can also 1) only extract HR patches 2) generate the LR patches by downsampling.

**Comment by yaolugithub** [comment]
Thank for your reply.
I have extrcted HR patches from DIV2K800 and generated LR patches by downsampling as you said.
I set parameters  
   crop_sz = 128
    step = 120
    thres_sz = 48  in extract_subimgs_single.py when performing x4 downsample , i want to know if  it  is  proper to do this? Could you give some suggestions? thanks.

**Comment by xinntao** [comment]
This step is just to accelerate the IO speed. So only extracting the original images to sub-images is enough. 
I think it is unnecessary to use crop size 128 if the training patch size is 128. 480 is OK.

**Comment by yaolugithub** [comment]
Hi. Thank you very much for your patient reply.
     I was confused about your reply "  I think it is unnecessary to use crop size 128 if the training patch size is 128. 480 is OK. "
     You mean that  i should set parameters crop_sz =480, step=120 OR crop_sz = 128,step =480  OR crop_sz =480, step =240 when peforming x4 downsampling from the original DIV2K800 images.
     I may be a little silly. Looking forward  to your reply.  thanks.

**Comment by yaolugithub** [comment]
Hi, xintao.
    Thank you very much for your patience. In addition, congratulations on
winning the 2019NTIRE Video Restoration and Enhancement Championship. I
will also continue to follow your work.
     I would like to ask a question. I cut the image of HR from the
original image of DIV2K according to the default setting of
train_ESRGAN.json file (crop_sz=480, step=240); then downsampled to get LR
image; 32208 images of HR and LR are obtained.
    But when running python train.py -opt options/train/train_ESRGAN.json,
the following error occurred:
Traceback (most recent call last):
File "train.py", line 173, in
Main()
File "train.py", line 74, in main
Val_set = create_dataset(dataset_opt)
File "/home/ylu/ESRGAN-BasicSR/codes/data/init.py", line 33, in
create_dataset
Dataset = D(dataset_opt)
File "/home/ylu/ESRGAN-BasicSR/codes/data/LRHR_dataset.py", line 40, in init
Len(self.paths_LR), len(self.paths_HR))
AssertionError: HR and LR datasets have different number of images - 14, 56.
(dataroot_HR of val in train_ESRGAN.json is set14/HR)


    But when I changed Set14 to Set5, there was no such problem.
    My analysis is a problem with the val dataset, but I haven't figured
out the specific reasons.May I  know what you think about it? And how to
use val Set14 ?
    thanks .


Here is part about my train_ESRGAN.json .The rest  i did not change.
{
  "name": "002_RRDB_ESRGAN_x4_DIV2K" //  please remove "debug_" during
training
  , "use_tb_logger": true
  , "model":"srragan"
  , "scale": 4
  , "gpu_ids": [0]

  , "datasets": {
    "train": {
      "name": "DIV2K"
      , "mode": "LRHR"
      , "dataroot_HR":
"/home/yaolu/dataset/ESRGAN_Data/DIV2K800_sub_HR.lmdb"
      , "dataroot_LR":
"/home/yaolu/dataset/ESRGAN_Data/DIV2K800_sub_LRx4.lmdb"
      , "subset_file": null
      , "use_shuffle": true
      , "n_workers": 8
      , "batch_size": 16
      , "HR_size": 128
      , "use_flip": true
      , "use_rot": true
    }
    , "val": {
      "name": "val_set14_part"
      , "mode": "LRHR"
      , "dataroot_HR": "/home/yaolu/dataset/Set5/HR"
      , "dataroot_LR": "/home/yaolu/dataset/Set5/LR_bicubic/X4"
    }
  }

  , "path": {
    "root": "/home/yaolu/ESRGAN-BasicSR"
    // , "resume_state":
"../experiments/debug_002_RRDB_ESRGAN_x4_DIV2K/training_state/16.state"
    , "pretrain_model_G":
"../experiments/pretrained_models/RRDB_PSNR_x4.pth"
  }











Xintao <notifications@github.com> 于2019年5月20日周一 上午2:00写道：

**Comment by yaolugithub** [comment]
Thanks for your patient reply.
I was confused about  what you said" I think it is unnecessary to use crop size 128 if the training patch size is 128. 480 is OK."     
I think crop_sz is training patch size.  So, i want to ask  how to set step (crop_sz =128  as in paper) when reproducing your paper?  Beasure step size affects the number of training patches.

In addition,  what validation set do you use ? DIV2K_valid?  In the paper, you specify the traing set is  DIV2K, Flickr2K and  OST ; test set is Set5, Set14 etc,  
thanks.

**Comment by xinntao** [comment]
crop_sz can be larger than patch size and it is better to set crop_sz to be larger than patch size. 

I usually use part of Set14 as the val datasets.

**Comment by yaolugithub** [comment]
I sincerely thanks for your multiple reponses.  Good luck with you.

**Comment by yaolugithub** [comment]
Thanks a lot.
You are so kind to me.

Wish you all the best.

Yaolu.

Xintao <notifications@github.com> 于2019年5月28日周二 下午5:33写道：
