### ISSUE TITLE
ValueError: cannot reshape array of size 32768 into shape (64,64,4)

### ISSUE THREAD

**Issue by SlimRG** [xinntao/BasicSR#137]
```
19-05-24 07:26:54.637 - INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "train.py", line 173, in <module>
    main()
  File "train.py", line 97, in main
    for _, train_data in enumerate(train_loader):
  File "/home/igor/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/igor/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/igor/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/igor/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/igor/neuron/BasicSR-master/codes/data/LRHR_dataset.py", line 51, in __getitem__
    img_HR = util.read_img(self.HR_env, HR_path)
  File "/home/igor/neuron/BasicSR-master/codes/data/util.py", line 78, in read_img
    img = _read_lmdb_img(env, path)
  File "/home/igor/neuron/BasicSR-master/codes/data/util.py", line 68, in _read_lmdb_img
    img = img_flat.reshape(H, W, C)
ValueError: cannot reshape array of size 32768 into shape (64,64,4)

```

**Comment by SlimRG** [comment]
![apple](https://user-images.githubusercontent.com/39348033/58303145-80a1eb00-7df7-11e9-84f9-11d16166cd65.png)
![apple](https://user-images.githubusercontent.com/39348033/58303151-88618f80-7df7-11e9-9ffa-afa352cadf7b.png)

**Comment by xinntao** [comment]
It seems that your data has some problems. Check the image size and the corresponding meta info in the lmdb file.

**Comment by SlimRG** [comment]
The was with this things^
1) LMDB doesn't work property on Windows OS
2) PyTorch without CUDA has some bugs on Windows OS if PC have more than one socket
3) Neuron Network doesn't work with alpha layout

**Comment by xinntao** [comment]
Thanks. 
It seems that it is better to use PyTorch in Ubuntu than windows. =_=
