### ISSUE TITLE
ERROR in training

### ISSUE THREAD

**Issue by peiyingxin** [xinntao/BasicSR#159]

**Comment by peiyingxin** [comment]
Traceback (most recent call last):
  File "train.py", line 175, in <module>
    main()
  File "train.py", line 49, in main
    tb_logger = SummaryWriter(log_dir='../tb_logger/' + opt['name'])
  File "C:\Program Files\Python36\lib\site-packages\tensorboardX\writer.py", line 254, in __init__
    self._get_file_writer()
  File "C:\Program Files\Python36\lib\site-packages\tensorboardX\writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'
i try to find the solution but failed.

**Comment by xinntao** [comment]
I have not encountered this problem in my environment. 
You may try to replace 'log_dir' with `logdir`, as the demo shows:
https://github.com/lanpa/tensorboardX/blob/bf8c6795779fbf225a6bbfefb5a53f9191e7440e/examples/demo_purge.py#L4-L6

**Comment by peiyingxin** [comment]
> I have not encountered this problem in my environment.
> You may try to replace 'log_dir' with `logdir`, as the demo shows:
> https://github.com/lanpa/tensorboardX/blob/bf8c6795779fbf225a6bbfefb5a53f9191e7440e/examples/demo_purge.py#L4-L6

thank you for your reply!  thank you very much!
now i want to use gray image to train not RGB image. How can i change the parameter?
And i want to generate X2 image not X4, how can i get the pretrain_model_G? without pretrain_model_G is ok?
thank you very much!!!

**Comment by xinntao** [comment]
1. add an extra config to dataset `color: gray`.
2. You can train from scratch or initialize it from the X4 model.

**Comment by peiyingxin** [comment]
> 1. add an extra config to dataset `color: gray`.
> 2. You can train from scratch or initialize it from the X4 model.

Dear xintao:
    thank you for you reply! 
    when i want to train X2 module, i meet the problem which is 
UserWarning: Using a target size (torch.Size([16, 3, 128, 128])) that is different to the input size (torch.Size([16, 3, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
    when i modify the GT_size: 256 instead of 128 in train_ESRGAN.yml , another problem 
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 22.41 GiB total capacity; 21.34 GiB already allocated; 10.38 MiB free; 21.20 MiB cached)
i'm a newer in this field, thank you for your Excellent work.thank you!

**Comment by xinntao** [comment]
You also need to modify `scale: 4`, `upscale: 4` for the X2 model.

**Comment by peiyingxin** [comment]
> You also need to modify `scale: 4`, `upscale: 4` for the X2 model.

hi,xintao:
        i have modify scale:4 into scale:2 , upscale:4 into upscale:2 ; but it still wrong:
UserWarning: Using a target size (torch.Size([16, 3, 128, 128])) that is different to the input size (torch.Size([16, 3, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
can you tell me Where do I need to make detailed changes?
thank you very much!!!

**Comment by xinntao** [comment]
Make sure that your output size is the same as your target. 
1. Check your input size.
2. Check the upsample scale factor of your network.

**Comment by peiyingxin** [comment]
> Make sure that your output size is the same as your target.
> 
> 1. Check your input size.
> 2. Check the upsample scale factor of your network.

thanks for your reply!!!
best wishes for you.

**Comment by 1810325** [comment]
@xinntao 您好我现在特别需要训练自己的模型，应为直接用作者的模型测试效果实在不好，但是我不知道该如何做，您能教我一下吗，任何提示将不盛感激，如果可以也可以加我微信love_qinging

**Comment by xinntao** [comment]
@1810325 
Prepare your data and finetune the pre-trained model.
