### ISSUE TITLE
File Not Found Error

### ISSUE THREAD

**Issue by freedyfreeds** [xinntao/BasicSR#163]

**Comment by freedyfreeds** [comment]
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 107, in main
    train_set = create_dataset(dataset_opt)
  File "/mnt/c/Users/DavidFriedman/Documents/GAN PROJECTS/ESRTrain/BasicSR/codes/data/__init__.py", line 38, in create_dataset
    dataset = D(dataset_opt)
  File "/mnt/c/Users/DavidFriedman/Documents/GAN PROJECTS/ESRTrain/BasicSR/codes/data/LQGT_dataset.py", line 25, in __init__
    self.paths_GT, self.sizes_GT = util.get_image_paths(self.data_type, opt['dataroot_GT'])
  File "/mnt/c/Users/DavidFriedman/Documents/GAN PROJECTS/ESRTrain/BasicSR/codes/data/util.py", line 50, in get_image_paths
    paths, sizes = _get_paths_from_lmdb(dataroot)
  File "/mnt/c/Users/DavidFriedman/Documents/GAN PROJECTS/ESRTrain/BasicSR/codes/data/util.py", line 36, in _get_paths_from_lmdb
    meta_info = pickle.load(open(os.path.join(dataroot, 'meta_info.pkl'), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/DavidFriedman/Pictures/Datasets/SplitDatasets/repository/BigPics.lmdb/meta_info.pkl'
