### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by freedyfreeds** [xinntao/BasicSR#166]
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.17 GiB total capacity; 10.60 GiB already allocated; 2.12 MiB free; 275.45 MiB cached)

**Comment by freedyfreeds** [comment]
Why do I get this?

**Comment by xinntao** [comment]
The model needs more GPU memory. 
You can decrease the training patch size or the batch size.

**Comment by freedyfreeds** [comment]
I have multiple GPUs available, can I somehow train using multiple GPUs? It seems as though it is only running on a single GPU.

**Comment by xinntao** [comment]
Yes, the updated version of BasicSR support multi-GPU training. The command is in https://github.com/xinntao/BasicSR/blob/master/codes/run_scripts.sh

But for multi-GPU training, there exists better training schemes. Currently, we just reuse the same learning scheme as single-GPU training.

**Comment by TheLostIn** [comment]
> Yes, the updated version of BasicSR support multi-GPU training. The command is in https://github.com/xinntao/BasicSR/blob/master/codes/run_scripts.sh
> 
> But for multi-GPU training, there exists better training schemes. Currently, we just reuse the same learning scheme as single-GPU training.

Hello,I ran the script and change batch_size into 8,16,64,but it all went wrong.
```
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    main()
  File "train.py", line 137, in main
    model = create_model(opt)
  File "/home/erestu/erestu/works/SR/BasicSR/codes/models/__init__.py", line 16, in create_model
    m = M(opt)
  File "/home/erestu/erestu/works/SR/BasicSR/codes/models/SRGAN_model_erestu.py", line 24, in __init__
    self.netG = networks.define_G(opt).to(self.device)
  File "/home/erestu/anaconda2/envs/torch1.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 432, in to
    return self._apply(convert)
  File "/home/erestu/anaconda2/envs/torch1.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 208, in _apply
    module._apply(fn)
  File "/home/erestu/anaconda2/envs/torch1.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 230, in _apply
    param_applied = fn(param)
  File "/home/erestu/anaconda2/envs/torch1.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 430, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: out of memory
```
How can I solve it?
