### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for RRDBNet: 	Missing key(s) in state_dict

### ISSUE THREAD

**Issue by MAdil45** [xinntao/BasicSR#170]
Hi. Hope you will be doing great. Excellent work with the ESRGAN. However, i need little help. I retrained the PSNR model on my dataset with the following settings.

"model":"sr"
"which_model_G": "sr_resnet" // RRDB_net | sr_resnet
"lr_G": 2e-4    As you described in the paper.
With "L1" loss, 
After training, when i try to train the model with the  initialization of PSNR model for the generator network with the following settings,
"model":"srragan"
"pretrain_model_G": "../experiments/pretrained_models/RRDB_PSNR_x4.pth"
"which_model_G": "RRDB_net " // RRDB_net | sr_resnet
"lr_G": 1e-4  
and also with the "L1" loss, i am getting following error. Can you please give me any suggestion how to remove this error. I will reaally appreciate it.

Traceback (most recent call last):
  File "train.py", line 172, in <module>
    main()
  File "train.py", line 82, in main
    model = create_model(opt)
  File "/home/adil/Desktop/Research_Work/Retraining_ESRGAN/BasicSR-master/codes/models/__init__.py", line 18, in create_model
    m = M(opt)
  File "/home/adil/Desktop/Research_Work/Retraining_ESRGAN/BasicSR-master/codes/models/SRRaGAN_model.py", line 26, in __init__
    self.load()  # load G and D if needed
  File "/home/adil/Desktop/Research_Work/Retraining_ESRGAN/BasicSR-master/codes/models/SRRaGAN_model.py", line 243, in load
    self.load_network(load_path_G, self.netG)
  File "/home/adil/Desktop/Research_Work/Retraining_ESRGAN/BasicSR-master/codes/models/base_model.py", line 63, in load_network
    network.load_state_dict(torch.load(load_path), strict=strict)
  File "/home/adil/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RRDBNet:
	Missing key(s) in state_dict: "model.1.sub.0.RDB1.conv1.0.weight", "model.1.sub.0.RDB1.conv1.0.bias", "model.1.sub.0.RDB1.conv2.0.weight", "model.1.sub.0.RDB1.conv2.0.bias", "model.1.sub.0.RDB1.conv3.0.weight", "model.1.sub.0.RDB1.conv3.0.bias", "model.1.sub.0.RDB1.conv4.0.weight",

**Comment by xinntao** [comment]
We have updated the code, you may need to download new pretrained models from https://drive.google.com/drive/u/0/folders/17VYV_SoZZesU6mbxz2dMAIccSSlqLecY  , without the `old_arch`

**Comment by MAdil45** [comment]
Thank U so much for your response. However i want to train PSNR oriented model on my dataset.  So that i can use it as an initialization for the training of generator network on my dataset.  I did train it but during initialization ,i got an error.  Can you please give me suggestion to remove this error. (P.S. I am new to this, so kindly excuse me if i am bothering you.). Thanks.

**Comment by xinntao** [comment]
The error `RuntimeError: Error(s) in loading state_dict for RRDBNet:
Missing key(s) in state_dict: ` is caused by the mismatching parameter names between the pre-trained model and the constructed model from codes. 
So make sure they have the same names. 

From your config file, you used an older version of BasicSR (with JSON config file), so you need to use the pre-trained model with `old_arch` and also change the `"pretrain_model_G": "../experiments/pretrained_models/RRDB_PSNR_x4.pth"` to `"pretrain_model_G": "../experiments/pretrained_models/RRDB_PSNR_x4_old_arch.pth"`.

As an alternative, you can use the updated codes of BasicSR.

**Comment by MAdil45** [comment]
@xinntao Thank You so much Brother. I appreciate that. I will try to use updated codes.
