### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by WANG-1173** [xinntao/BasicSR#183]
Hello!
When I'm done with this： python codes/train.py -opt ./codes/options/train/train_ESRGAN.json
, remind me：
19-07-17 11:22:11.796 - INFO: Random seed: 0
19-07-17 11:22:11.932 - INFO: Dataset [LRHRDataset - DIV2K] is created.
19-07-17 11:22:11.932 - INFO: Number of train images: 800, iters: 50
19-07-17 11:22:11.932 - INFO: Total epochs needed: 10000 for iters 500,000
19-07-17 11:22:11.933 - INFO: Dataset [LRHRDataset - val_set14_part] is created.
19-07-17 11:22:11.934 - INFO: Number of val images in [val_set14_part]: 13
19-07-17 11:22:12.716 - INFO: Initialization method [kaiming]
19-07-17 11:22:24.902 - INFO: Initialization method [kaiming]
19-07-17 11:22:25.935 - INFO: Loading pretrained model for G [/public/home/G19850028/q         ingwei/A/BasicSR-master/experiments/pretrained_models/RRDB_ESRGAN_x4_old_arch.pth] ...
Downloading: "https://download.pytorch.org/models/vgg19-dcbb9e9d.pth" to /public/home/         G19850028/.torch/models/vgg19-dcbb9e9d.pth
Traceback (most recent call last):
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/public/home/G19850028/zheng/Anacoda3/public/home/G19850028/anacoda35/envs/pytorch1.0/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

This is running on the school server. How to solve this problem?Thank you very much

**Comment by WANG-1173** [comment]
thank u！i have solved the problem
