### ISSUE TITLE
Size about LR pictures

### ISSUE THREAD

**Issue by yangyingni** [xinntao/BasicSR#239]
Hello,thank you for your work first.I have a question about the size of lr pictures.I want to ask whether i can use 128*128 hr pictures and 8x downsampled lr pictures(16*16),i changed all scale_ratio correctly and when i ran create_lmdb.py,it shows
         **lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached**

I can get ../dataset/DIK2K/DIV2K800_sub_bicLRx8.lmdb  and ../dataset/DIK2K/DIV2K800_sub.lmdb,but no meta_info.pkl under DIV2K800_sub_bicLRx8.lmdb.Can you tell me why?Thank you.

**Comment by yangyingni** [comment]
> Hello,thank you for your work first.I have a question about the size of lr pictures.I want to ask whether i can use 128128 hr pictures and 8x downsampled lr pictures(1616),i changed all scale_ratio correctly and when i ran create_lmdb.py,it shows
> lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached
> I can get ../dataset/DIK2K/DIV2K800_sub_bicLRx8.lmdb  and ../dataset/DIK2K/DIV2K800_sub.lmdb,but no meta_info.pkl under DIV2K800_sub_bicLRx8.lmdb.Can you tell me why?Thank you.

When i run python create_lmdb.py,it shows
Traceback (most recent call last):
  File "create_lmdb.py", line 411, in <module>
    main()
  File "create_lmdb.py", line 44, in main
    general_image_folder(opt)
  File "create_lmdb.py", line 120, in general_image_folder
    txn.put(key_byte, data)
lmdb.MapFullError: mdb_put: MDB_MAP_FULL: Environment mapsize limit reached
