### ISSUE TITLE
no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by ManoaNosea** [xinntao/BasicSR#240]
```20-02-17 22:27:54.874 - INFO: Model [SRModel] is created.
20-02-17 22:27:54.874 - INFO: Start training from epoch: 0, iter: 0
E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\optim\lr_scheduler.py:122: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
THCudaCheck FAIL file=C:/w/1/s/windows/pytorch/aten/src\THCUNN/generic/LeakyReLU.cu line=29 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "train.py", line 232, in <module>
    main()
  File "train.py", line 161, in main
    model.optimize_parameters(current_step)
  File "F:\BasicSR-master\codes\models\SR_model.py", line 91, in optimize_parameters
    self.fake_H = self.netG(self.var_L)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\BasicSR-master\codes\models\modules\SRResNet_arch.py", line 42, in forward
    fea = self.lrelu(self.conv_first(x))
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\modules\activation.py", line 559, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "E:\programs\WPy64-3680\python-3.6.8.amd64\lib\site-packages\torch\nn\functional.py", line 1061, in leaky_relu
    result = torch._C._nn.leaky_relu_(input, negative_slope)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at C:/w/1/s/windows/pytorch/aten/src\THCUNN/generic/LeakyReLU.cu:29

**Comment by ManoaNosea** [comment]
fixed with
```pip3 install torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html

refer to https://pytorch.org/get-started/previous-versions/ for your specific version of CUDA/torch combination :)
