### ISSUE TITLE
error while installing mmcv

### ISSUE THREAD

**Issue by alekspickle** [xinntao/BasicSR#273]
I stumbled upon this error while running `python3 setup.py develop` cmd.

<details>
<summary>Full stacktrace</summary>

Installed /home/pickle/Documents/data/BasicSR
Processing dependencies for basicsr==1.0.0+906d72a
Searching for mmcv>=0.6
Reading https://pypi.org/simple/mmcv/
Downloading https://files.pythonhosted.org/packages/7e/0f/71adf51180d7afabe790482f1c8f1129ab6b6fcc7bc7c010691ab67c936f/mmcv-1.1.1.tar.gz#sha256=83a3c75e1250a6f066adb4cbd88933b26d5e2dd278c08ac9955b82c5ca0d5690
Best match: mmcv 1.1.1
Processing mmcv-1.1.1.tar.gz
Writing /tmp/easy_install-1pkx_nrz/mmcv-1.1.1/setup.cfg
Running mmcv-1.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1pkx_nrz/mmcv-1.1.1/egg-dist-tmp-jlcdvd9e
Traceback (most recent call last):
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-1pkx_nrz/mmcv-1.1.1/setup.py", line 194, in <module>
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    self.run_command("egg_info")
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 297, in run
    self.find_sources()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
    mm.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 535, in run
    self.add_defaults()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
    sdist.add_defaults(self)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 339, in finalize_options
    super().finalize_options()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 144, in finalize_options
    self.check_extensions_list(self.extensions)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 362, in check_extensions_list
    raise DistutilsSetupError(
distutils.errors.DistutilsSetupError: each element of 'ext_modules' option must be an Extension instance or 2-tuple

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 122, in <module>
    setup(
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 155, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 779, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1064, in best_match
    return self.obtain(req, installer)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1076, in obtain
    return installer(requirement)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 686, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 712, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 897, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1167, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1151, in run_setup
    run_setup(setup_script, args)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-1pkx_nrz/mmcv-1.1.1/setup.py", line 194, in <module>
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
    return distutils.core.setup(**attrs)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    self.run_command("egg_info")
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 297, in run
    self.find_sources()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 304, in find_sources
    mm.run()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 535, in run
    self.add_defaults()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 571, in add_defaults
    sdist.add_defaults(self)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 339, in finalize_options
    super().finalize_options()
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 144, in finalize_options
    self.check_extensions_list(self.extensions)
  File "/home/pickle/Documents/data/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 362, in check_extensions_list
    raise DistutilsSetupError(
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple")
</details>

**Comment by xinntao** [comment]
Try to install mmcv separately:
`pip install mmcv`

**Comment by alekspickle** [comment]
Yep, that the trick!
