### ISSUE TITLE
ESRGAN cannot be trained with distributing training?

### ISSUE THREAD

**Issue by chy8855** [xinntao/BasicSR#277]
Hi, Xintao. Thanks for your wonderful work about ESRGAN. I meet a question when use distribution training ESRGAN, while other works like MSRResNet, RRDBNet_PSNR support distributing training .
  it seems that GAN dont support distribution training
some log:
    print_freq: 100
    save_checkpoint_freq: 5000.0
    use_tb_logger: True
    wandb:[
      project: None
      resume_id: None
    ]
  ]
  dist_params:[
    backend: nccl
    port: 29500
  ]
  is_train: True
  dist: True
  rank: 0
  world_size: 8

2020-08-31 14:10:40,304 INFO: Random seed: 0
Traceback (most recent call last):
  File "/home/sunlj/anaconda3/envs/yolo/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sunlj/anaconda3/envs/yolo/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sunlj/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/sunlj/anaconda3/envs/yolo/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/sunlj/anaconda3/envs/yolo/bin/python', '-u', 'basicsr/train.py', '--local_rank=7', '-opt', 'options/train/ESRGAN/train_ESRGAN_x4.yml', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by xinntao** [comment]
Thanks, this is a bug. 
I have fixed it. Now the master branch is OK for ESRGAN dist training
Ref: #278
