### ISSUE TITLE
About SRGAN_model.py optimize_parameters

### ISSUE THREAD

**Issue by House-Leo** [xinntao/BasicSR#295]
I have two different input folders and I want to use two optimizer in different weight to update parameters.
Like when input is folder_1, use optimizer_1.
I want to realize that. Is define another optimizer in SRGAN_model.py work? 
`def optimize_parameters_1(self, step):`
`def optimize_parameters_2(self, step):`

**Comment by xinntao** [comment]
I think you can do so. 

OR
init two optimizers in the `setup_optimizers` function and choose in the `optimize_parameters` function according to the datasets

Maybe you can also achieve this by using different loss weights for different dataset (not exactly as what you want)

**Comment by House-Leo** [comment]
Thanks for your answer! I would try to do it.

**Comment by House-Leo** [comment]
Thanks for your answer! I will try to do it.

**Comment by House-Leo** [comment]
`           wd_G = train_opt['weight_decay_G'] if train_opt['weight_decay_G'] else 0
            optim_params = []
            optim_params_2 = []
            for k, v in self.netG.named_parameters():  # can optimize for a part of the model
                if 'Res_trunk_2' in k:
                    v.requires_grad = False
                if v.requires_grad:
                    optim_params.append(v)
                v.requires_grad = True
                #else:
                #    if self.rank <= 0:
                #        logger.warning('Params [{:s}] will not optimize.'.format(k))
                if 'Res_trunk_1' in k :
                    v.requires_grad = False
                if v.requires_grad:
                    optim_params_2.append(v)
                v.requires_grad = True

            self.optimizer_G1 = torch.optim.Adam(optim_params, lr=train_opt['lr_G'],
                                                weight_decay=wd_G,
                                                betas=(train_opt['beta1_G'], train_opt['beta2_G']))
            self.optimizers.append(self.optimizer_G1)

            self.optimizer_G2 = torch.optim.Adam(optim_params_2, lr=train_opt['lr_G'],
                                                weight_decay=wd_G,
                                                betas=(train_opt['beta1_G'], train_opt['beta2_G']))
            self.optimizers.append(self.optimizer_G2)`
I try to init two optimizers like this. And two`optimize_parameters` only change the weight.
`def optimize_parameters_1(self, step):
       ...       
       self.optimizer_G1.zero_grad()
       ...
            self.optimizer_G1.step()`
`def optimize_parameters_2(self, step):
       ...       
       self.optimizer_G2.zero_grad()
       ...
            self.optimizer_G2.step()`
In the `train.py`, we have
`for _, train_data in enumerate(train_loader_1):
      ...
            model.update_learning_rate(current_step, warmup_iter=opt['train']['warmup_iter']) 
            model.feed_data(train_data)
            model.optimize_parameters_1(current_step)`
`for _, train_data in enumerate(train_loader_2):
      ...
            model.update_learning_rate(current_step, warmup_iter=opt['train']['warmup_iter'])   
            model.feed_data(train_data)
            model.optimize_parameters_2(current_step)`

But got the error in the second dataloader.
`Traceback (most recent call last):
  File "train_new.py", line 328, in <module>
    main()
  File "train_new.py", line 250, in main
    model.optimize_parameters_2(current_step)
  File "/home/yzj6850/HouseLee/Real-SR-master/codes/models/SRGAN_model.py", line 246, in optimize_parameters_2
    self.cri_gan(pred_g_fake - torch.mean(pred_d_real), True)) / 2
TypeError: unsupported operand type(s) for *: 'NoneType' and 'Tensor'`
Do you know how to fix it? Thanks!
