### ISSUE TITLE
Undefined symbol Z17fused_ error 

### ISSUE THREAD

**Issue by deepfacebrasil** [xinntao/BasicSR#299]
I had this erros and I cannot fix it. Someone can help me

`Traceback (most recent call last):
  File "tests/test_face_dfdnet.py", line 12, in <module>
    from basicsr.models.archs.dfdnet_arch import DFDNet
  File "/home/bruno/BasicSR/basicsr/models/__init__.py", line 16, in <module>
    _model_modules = [
  File "/home/bruno/BasicSR/basicsr/models/__init__.py", line 17, in <listcomp>
    importlib.import_module(f'basicsr.models.{file_name}')
  File "/home/bruno/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bruno/BasicSR/basicsr/models/video_gan_model.py", line 1, in <module>
    from basicsr.models.srgan_model import SRGANModel
  File "/home/bruno/BasicSR/basicsr/models/srgan_model.py", line 6, in <module>
    from basicsr.models.archs import define_network
  File "/home/bruno/BasicSR/basicsr/models/archs/__init__.py", line 14, in <module>
    _arch_modules = [
  File "/home/bruno/BasicSR/basicsr/models/archs/__init__.py", line 15, in <listcomp>
    importlib.import_module(f'basicsr.models.archs.{file_name}')
  File "/home/bruno/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bruno/BasicSR/basicsr/models/archs/stylegan2_arch.py", line 7, in <module>
    from basicsr.models.ops.fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/bruno/BasicSR/basicsr/models/ops/fused_act/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/bruno/BasicSR/basicsr/models/ops/fused_act/fused_act.py", line 7, in <module>
    from . import fused_act_ext
ImportError: /home/bruno/BasicSR/basicsr/models/ops/fused_act/fused_act_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z17fused_bias_act_opRKN2at6TensorES2_S2_iiff
`

**Comment by xinntao** [comment]
@brazilgithub 

It seems that the compilataion of fused_act failed. 

May check your gcc version, CUDA version.
