### ISSUE TITLE
Error on initializing dataloader ?

### ISSUE THREAD

**Issue by onurctirtir** [xinntao/BasicSR#3]
When I try to use urban100 with SFTGAN, I get the following error:

Traceback (most recent call last):
  File "train.py", line 157, in <module>
    main()
  File "train.py", line 71, in main
    for i, train_data in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/onurctirtir/Desktop/BasicSR/codes/data/LRHR_seg_bg_dataset.py", line 58, in __getitem__
    seg = torch.load(HR_path.replace('/img/', '/bicseg/').replace('.png', '.pth'))
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 301, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/onurctirtir/Desktop/datasets/urban100/img_002.pth'

Why do you prefer such a renaming from "png" to "pth" while loading data ? 
"seg = torch.load(HR_path.replace('/img/', '/bicseg/').replace('.png', '.pth'))"

**Comment by xinntao** [comment]
@onurctirtir It could not find the files.
Before running SFTGAN, intermediate segmentation results should be prepared first. (run test_seg.py (only the predefined categories are support) OR train a new segmentation model.)

After getting the segmentation results, put them in a proper folder. The path should be the same as seg = torch.load(HR_path.replace('/img/', '/bicseg/').replace('.png', '.pth')) or modify this line of code.
