### ISSUE TITLE
TypeError: DCNv2Pack() takes no arguments

### ISSUE THREAD

**Issue by QuantumLiu** [xinntao/BasicSR#331]
Got error while trying to test(inference) EDVR on my own video frames data.
pytorch:1.4.0
```
~/pyprojects/BasicSR$ python basicsr/test.py -opt options/test/EDVR/test_EDVR_L_deblurcomp_REDS.yml
Cannot import dcn. Ignore this warning if dcn is not used. Otherwise install BasicSR with compiling dcn.
Cannot import fused_act and upfirdn2d. Ignore this warning if they are not used. Otherwise install BasicSR with compiling them.
Disable distributed.
Path already exists. Rename it to /home/re01/pyprojects/BasicSR/results/EDVR_L_REDS_deblurcomp_official_archived_20201116_001945
2020-11-16 00:19:45,253 INFO: 
                ____                _       _____  ____
               / __ ) ____ _ _____ (_)_____/ ___/ / __ \
              / __  |/ __ `// ___// // ___/\__ \ / /_/ /
             / /_/ // /_/ /(__  )/ // /__ ___/ // _, _/
            /_____/ \__,_//____//_/ \___//____//_/ |_|
     ______                   __   __                 __      __
    / ____/____   ____   ____/ /  / /   __  __ _____ / /__   / /
   / / __ / __ \ / __ \ / __  /  / /   / / / // ___// //_/  / /
  / /_/ // /_/ // /_/ // /_/ /  / /___/ /_/ // /__ / /<    /_/
  \____/ \____/ \____/ \____/  /_____/\____/ \___//_/|_|  (_)
    
Version Information: 
        BasicSR: 1.1.1+58d7555
        PyTorch: 1.4.0
        TorchVision: 0.5.0
2020-11-16 00:19:45,253 INFO: 
  name: EDVR_L_REDS_deblurcomp_official
  model_type: EDVRModel
  scale: 1
  num_gpu: 1
  manual_seed: 0
  datasets:[
    test:[
      name: REDS4
      type: VideoTestDataset
      dataroot_gt: /media/re01/DATA_3/SR/lq_mv_seqs
      dataroot_lq: /media/re01/DATA_3/SR/lq_mv_seqs
      meta_info_file: info_lq_mv.txt
      io_backend:[
        type: disk
      ]
      cache_data: False
      num_frame: 5
      padding: replicate
      phase: test
      scale: 1
    ]
  ]
  network_g:[
    type: EDVR
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 128
    num_frame: 5
    deformable_groups: 8
    num_extract_block: 5
    num_reconstruct_block: 40
    center_frame_idx: None
    hr_in: True
    with_predeblur: True
    with_tsa: True
  ]
  path:[
    pretrain_network_g: experiments/pretrained_models/EDVR/EDVR_L_deblurcomp_REDS_official-0e988e5c.pth
    strict_load_g: True
    results_root: /home/re01/pyprojects/BasicSR/results/EDVR_L_REDS_deblurcomp_official
    root: /home/re01/pyprojects/BasicSR
    log: /home/re01/pyprojects/BasicSR/results/EDVR_L_REDS_deblurcomp_official
    visualization: /home/re01/pyprojects/BasicSR/results/EDVR_L_REDS_deblurcomp_official/visualization
  ]
  val:[
    save_img: True
    suffix: None
    metrics:[
      psnr:[
        type: calculate_psnr
        crop_border: 0
        test_y_channel: False
      ]
    ]
  ]
  is_train: False
  dist: False
  rank: 0
  world_size: 1

2020-11-16 00:19:45,254 INFO: Generate data info for VideoTestDataset - REDS4
2020-11-16 00:19:45,702 INFO: Dataset VideoTestDataset - REDS4 is created.
2020-11-16 00:19:45,702 INFO: Number of test images in REDS4: 109043
Traceback (most recent call last):
  File "basicsr/test.py", line 58, in <module>
    main()
  File "basicsr/test.py", line 45, in main
    model = create_model(opt)
  File "/home/re01/pyprojects/BasicSR/basicsr/models/__init__.py", line 38, in create_model
    model = model_cls(opt)
  File "/home/re01/pyprojects/BasicSR/basicsr/models/edvr_model.py", line 17, in __init__
    super(EDVRModel, self).__init__(opt)
  File "/home/re01/pyprojects/BasicSR/basicsr/models/sr_model.py", line 23, in __init__
    self.net_g = define_network(deepcopy(opt['network_g']))
  File "/home/re01/pyprojects/BasicSR/basicsr/models/archs/__init__.py", line 45, in define_network
    net = dynamic_instantiation(_arch_modules, network_type, opt)
  File "/home/re01/pyprojects/BasicSR/basicsr/models/archs/__init__.py", line 40, in dynamic_instantiation
    return cls_(**opt)
  File "/home/re01/pyprojects/BasicSR/basicsr/models/archs/edvr_arch.py", line 336, in __init__
    num_feat=num_feat, deformable_groups=deformable_groups)
  File "/home/re01/pyprojects/BasicSR/basicsr/models/archs/edvr_arch.py", line 52, in __init__
    deformable_groups=deformable_groups)
TypeError: DCNv2Pack() takes no arguments
```

**Comment by jeejeeli** [comment]
Hi,how did you solve this problem？

**Comment by zbrnwpu** [comment]
hi,@QuantumLiu,Have you solved this problem?

**Comment by ALTNT** [comment]
> hi,@QuantumLiu,Have you solved this problem?@xinntao

请问你有解决这个问题吗？

**Comment by ChenhaoWang2000** [comment]
I have the same problem.

**Comment by dzy1997** [comment]
Same problem here

**Comment by T914-cool** [comment]
Same problem here

**Comment by bigyellowofhust** [comment]
hi,have you solved this problem?

**Comment by gulzainali98** [comment]
same error!

**Comment by Holmes2002** [comment]
Solotion : U miss the line code specify the CUDA paths 
```
CUDA_HOME=/usr/local/cuda \
CUDNN_INCLUDE_DIR=/usr/local/cuda \
CUDNN_LIB_DIR=/usr/local/cuda \
BASICSR_EXT=True python setup.py develop

```
