### ISSUE TITLE
Unable to predict on single channel images

### ISSUE THREAD

**Issue by purijs** [xinntao/BasicSR#360]
I was able to train the PSNR model for single channel image but it breaks in the prediction part. Any clue?

I'm passing `in_channel` and `out_channel` as 1 in the `yml` file, but it breaks with this log:

```
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (relu): ReLU(inplace=True)
    )
  )
  (upconv1): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (upconv2): Conv2d(64, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pixel_shuffle): PixelShuffle(upscale_factor=2)
  (conv_hr): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (conv_last): Conv2d(64, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (lrelu): LeakyReLU(negative_slope=0.1, inplace=True)
)
2021-01-26 09:10:03,507 INFO: Loading MSRResNet model from /home/jovyan/BasicSR/experiments/tif_nir_psnr_model/models/net_g_10000.pth.
2021-01-26 09:10:03,521 INFO: Model [SRModel] is created.
2021-01-26 09:10:03,521 INFO: Testing test_tif_nir_psnr_model...
  0%|                                                                                                                                                               | 0/550 [00:00<?, ?image/s]Traceback (most recent call last):
  File "test.py", line 59, in <module>
    main()
  File "test.py", line 51, in main
    model.validation(
  File "../basicsr/models/base_model.py", line 49, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger,
  File "../basicsr/models/sr_model.py", line 139, in nondist_validation
    self.test()
  File "../basicsr/models/sr_model.py", line 117, in test
    self.output = self.net_g(self.lq)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "../basicsr/models/archs/srresnet_arch.py", line 65, in forward
    feat = self.lrelu(self.conv_first(x))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 341, in conv2d_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Given groups=1, weight of size 64 1 3 3, expected input[1, 3, 32, 32] to have 1 channels, but got 3 channels instead
  0%|  
```

**Comment by msqiu** [comment]
Same problem, have you solved it?
