### ISSUE TITLE
How can I train x2 or x3 super resolution task?

### ISSUE THREAD

**Issue by rlgnswk** [xinntao/BasicSR#365]
Thanks for your github

I'll try to train x2 or x3 tasks

How can I train x2 or x3 super resolution task?

Is there only way for x4 task?

**Comment by themousepotato** [comment]
Hey, did you find the solution? I'm also trying to train it for x2 upscale got stuck with the following error:
```
/content/BasicSR/basicsr/models/losses/losses.py:15: UserWarning: Using a target size (torch.Size([16, 3, 128, 128])) that is different to the input size (torch.Size([16, 3, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(pred, target, reduction='none')
Traceback (most recent call last):
  File "basicsr/train.py", line 251, in <module>
    main()
  File "basicsr/train.py", line 210, in main
    model.optimize_parameters(current_iter)
  File "/content/BasicSR/basicsr/models/esrgan_model.py", line 27, in optimize_parameters
    l_g_pix = self.cri_pix(self.output, self.gt)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/BasicSR/basicsr/models/losses/losses.py", line 55, in forward
    pred, target, weight, reduction=self.reduction)
  File "/content/BasicSR/basicsr/models/losses/loss_util.py", line 91, in wrapper
    loss = loss_func(pred, target, **kwargs)
  File "/content/BasicSR/basicsr/models/losses/losses.py", line 15, in l1_loss
    return F.l1_loss(pred, target, reduction='none')
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2633, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 71, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3


```
