### ISSUE TITLE
Local variable 'val_loader' referenced before assignment when training with train_sr.json

### ISSUE THREAD

**Issue by Nimmerwoner** [xinntao/BasicSR#37]
Hello,

I encounter the error `UnboundLocalError: local variable 'val_loader' referenced before assignment` when trying to train SR. The execution command is `python train.py -opt options/train/train_sr.json`.

Do any one have an idea why this happens?

The full output and error is as follows and is encountered after iteration 8 in the validation phase:

```export CUDA_VISIBLE_DEVICES=0,1,2,3
Path already exists. Rename it to [/home/.../.../basicsr-xinntao/experiments/debug_001_RRDB_PSNR_x4_DIV2K_archived_181127-104642]
Random Seed:  0
Dataset [LRHRDataset - Sobolt] is created.
Number of train images: 9,687, iters: 606
Total epoches needed: 1651 for iters 1,000,000
initialization method [kaiming]
---------- Model initialized ------------------
Number of parameters in G: 16,697,987
-----------------------------------------
Model [SRModel] is created.
---------- Start training -------------
/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
<epoch:  0, iter:       2, time:1.31, lr:2.0e-04> l_pix: 4.21e-01
<epoch:  0, iter:       4, time:1.24, lr:2.0e-04> l_pix: 3.85e-01
<epoch:  0, iter:       6, time:1.24, lr:2.0e-04> l_pix: 3.41e-01 
<epoch:  0, iter:       8, time:1.25, lr:2.0e-04> l_pix: 2.01e-01 
Saving the model at the end of iter 8.
---------- validation -------------
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "train.py", line 106, in main
    for val_data in val_loader:
UnboundLocalError: local variable 'val_loader' referenced before assignment
```

I am using 4 GPUs, a batch_size of 16 with 8 n_workers and an HR_size of 512.

Any help is appreciated.

**Comment by Nimmerwoner** [comment]
Apologies. The error was a result from not having specified validation sets.
