### ISSUE TITLE
new issues about   No module named 'basicsr.version'

### ISSUE THREAD

**Issue by shuodie** [xinntao/BasicSR#407]
Traceback (most recent call last):
  File "/home/bme403/桌面/ws_SR/BasicSR-master/basicsr/train.py", line 10, in <module>
    from basicsr.data import build_dataloader, build_dataset
  File "/home/bme403/桌面/ws_SR/BasicSR-master/basicsr/__init__.py", line 12, in <module>
    from .version import __gitsha__, __version__
ModuleNotFoundError: No module named 'basicsr.version'

I changed the function   get_env_info()   according to the previous issue..., but the above error occurred

**Comment by xinntao** [comment]
@shuodie  have you installed basicsr?

**Comment by DachunKai** [comment]
> 我下载了basicsr,但也显示ModuleNotFoundError: No module named 'basicsr.version'

你的pip install basicsr或者python setup.py develop任何一个都没有跑

**Comment by cjw19951005** [comment]
> > 我下载了basicsr,但也显示ModuleNotFoundError: No module named 'basicsr.version'
> 
> 你的pip install basicsr或者python setup.py develop任何一个都没有跑

我已安装basicsr,setuo.py develop 也运行了

**Comment by ChengLiu-xsy** [comment]
我不清楚你这个是不是跟我的一样，我是之前只运行了pip install basicsr，然后就一直报ModuleNotFoundError: No module named 'basicsr.version'。我是后面在ide里面运行python setup.py develop才好的
