### ISSUE TITLE
error in training

### ISSUE THREAD

**Issue by mixtresh** [xinntao/BasicSR#46]
Traceback (most recent call last):
  File "C:/BasicSR/codes/train.py", line 158, in <module>
    main()
  File "C:/BasicSR/codes/train.py", line 22, in main
    opt = option.parse(parser.parse_args().opt, is_train=True)
  File "C:\BasicSR\codes\options\options.py", line 18, in parse
    opt = json.loads(json_str, object_pairs_hook=OrderedDict)
  File "C:\Users\Mixtresh\AppData\Local\Programs\Python\Python36\lib\json\__init
__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "C:\Users\Mixtresh\AppData\Local\Programs\Python\Python36\lib\json\decode
r.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Mixtresh\AppData\Local\Programs\Python\Python36\lib\json\decode
r.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

i run train on windows 8.1

**Comment by Titaniumtown** [comment]
I get this issue in python 3.6 ubuntu and windows I have tried everything please help!

**Comment by Titaniumtown** [comment]
found the issue in windows make a \ into \\
eg. C:\datasets\HR
turns into: C:\\datasets\\HR

**Comment by Titaniumtown** [comment]
nevermind even though I do that I get:
E:\projects\BasicSR\codes>python test.py -opt options/test/test_esrgan.json
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    opt = option.parse(parser.parse_args().opt, is_train=False)
  File "E:\projects\BasicSR\codes\options\options.py", line 18, in parse
    opt = json.loads(json_str, object_pairs_hook=OrderedDict)
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 76 column 1 (char 801)

**Comment by Titaniumtown** [comment]
it still seems to be something with it parsing back slashes

**Comment by Titaniumtown** [comment]
Yea I do not know how to make this work any ideas?

**Comment by Titaniumtown** [comment]
updated to latest version of BasicSR and did double backspaces and it worked!!
