### ISSUE TITLE
单GPU训练，程序运行过程中卡住。

### ISSUE THREAD

**Issue by zdyshine** [xinntao/BasicSR#475]
您好，最近使用BasicSR进行超分任务训练，使用:  
model_type: SRModel  
scale: 2  
num_gpu: 1  
manual_seed: 0，  
但是每次训练着，程序就卡住了，也不报错，也不继续执行。有卡在10w  iter，也有卡在35w iter。  
请问您有什么建议吗？或者可能的原因在哪？

**Comment by xinntao** [comment]
需要更多信息来判断

1. 如果在卡住的时候， 按ctrl+c 停止程序， 屏幕会显示它卡在哪里呢？
2. 使用PyTorch版本和BasicSR的版本是？

**Comment by zdyshine** [comment]
感谢回复！
版本信息:pytorch=1.8.0，BasicSR是上周直接git clone的，  
ctrl + c 后，显示如下：
Traceback (most recent call last):
  File "basicsr/train.py", line 212, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 158, in train_pipeline
    train_data = prefetcher.next()
  File "/test/BasicSR/basicsr/data/prefetch_dataloader.py", line 76, in next
    return next(self.loader)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1148, in _get_data
    success, data = self._try_get_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 107, in get
    if not self._poll(timeout):
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/opt/conda/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)

怀疑是加载数据的问题，目前更换了数据盘在训练了，但是不确定是不是有其他原因。

**Comment by xinntao** [comment]
这个目前看起来是 load 数据的问题， 后面如果还有问题， 可以提供进一步的信息~

**Comment by xinntao** [comment]
如果没有进一步的问题， 我就先close了， 如果后面有问题，再open哈~
