### ISSUE TITLE
KeyError: 'metrics'

### ISSUE THREAD

**Issue by chuckwoody** [xinntao/BasicSR#485]
2021-10-20 06:58:39,141 INFO: Loading RRDBNet model from experiments/pretrained_models/ESRGAN/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth, with param key: [params].
2021-10-20 06:58:39,358 INFO: Model [ESRGANModel] is created.
2021-10-20 06:58:39,358 INFO: Testing Set5...
Traceback (most recent call last):
  File "basicsr/test.py", line 45, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 40, in test_pipeline
    model.validation(test_loader, current_iter=opt['name'], tb_logger=None, save_img=opt['val']['save_img'])
  File "/content/drive/My Drive/BasicSR/basicsr/models/base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/content/drive/My Drive/BasicSR/basicsr/models/sr_model.py", line 144, in nondist_validation
    self._initialize_best_metric_results(dataset_name)
  File "/content/drive/My Drive/BasicSR/basicsr/models/base_model.py", line 60, in _initialize_best_metric_results
    for metric, content in self.opt['val']['metrics'].items():
KeyError: 'metrics'

**Comment by chuckwoody** [comment]
在Google colab 运行BasicSR_inference_ESRGAN.ipynb

**Comment by xinntao** [comment]
Thanks for reporting this issue. It should be fixed now. 

https://github.com/xinntao/BasicSR/commit/c1ab73ffbcadf1244c6731b4a71509d4e323b5b8

If you still have problems, please let me know. Thanks :-)
