### ISSUE TITLE
spawn.py issues

### ISSUE THREAD

**Issue by Titaniumtown** [xinntao/BasicSR#49]
when I run train.py I get:

```
19-01-02 21:35:49.755 - INFO: Model [SRRaGANModel] is created.
19-01-02 21:35:49.773 - INFO: Start training...
Traceback (most recent call last):
  File "train.py", line 154, in <module>
    main()
  File "train.py", line 79, in main
    for i, train_data in enumerate(train_loader):
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle Environment objects

E:\projects\BasicSR\codes>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Claes\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

I am running windows 10 home and python 3.6.8 gtx 1060 max q

**Comment by jnjaby** [comment]
Seems like it is a bug of Pytorch-windows. I would recommend you report this to Pytorch forum or switch your platform to Linux.

**Comment by DanielWeMs** [comment]
I have found that you can work around this by setting the n_workers to 0 and increase the batch size to at least one more than the number of images. PyTorch's multiprocess handling on Windows doesn't appear to be working very well right now.
