### ISSUE TITLE
关于训练中出现CV2.error问题

### ISSUE THREAD

**Issue by DHtsing** [xinntao/BasicSR#505]
`Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "train.py", line 216, in main
    train_data = prefetcher.next()
  File "/work/Users/dengdexin/BasicSR-master/basicsr/data/prefetch_dataloader.py", line 76, in next
    return next(self.loader)
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
**cv2.error: Caught error in DataLoader worker process 0.**
Original Traceback (most recent call last):
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/work/Users/dengdexin/BasicSR-master/basicsr/data/paired_image_dataset.py", line 82, in __getitem__
    img_gt = mmcv.imfrombytes(img_bytes).astype(np.float32) / 255.
  File "/home/dengdexin/miniconda3/envs/project/lib/python3.7/site-packages/mmcv/image/io.py", line 257, in imfrombytes
    img = cv2.imdecode(img_np, flag)
**cv2.error: OpenCV(4.5.4) /tmp/pip-req-build-3129w7z7/opencv/modules/imgcodecs/src/loadsave.cpp:814: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'**

`
当我配置好环境后，进行训练训练了900次迭代后出现了cv2.error，不知道什么原因导致的

**Comment by hhx67** [comment]
同样的问题，请问解决了吗

**Comment by OhGaGaGaGa** [comment]
可能 cuda out of memory 了
