### ISSUE TITLE
Error when running train.py

### ISSUE THREAD

**Issue by Ifinxx** [xinntao/BasicSR#56]
I get the following error when training. How can I resolve this?

19-01-13 23:26:40.218 - INFO: Model [SRRaGANModel] is created.
19-01-13 23:26:40.219 - INFO: Start training from epoch: 0, iter: 0
C:\Users\ToddS\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\train.py", line 173, in <module>
    main()
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\train.py", line 97, in main
    for _, train_data in enumerate(train_loader):
  File "C:\Users\ToddS\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "C:\Users\ToddS\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "C:\Users\ToddS\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\ToddS\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\data\LRHR_dataset.py", line 94, in __getitem__
    img_LR = util.imresize_np(img_HR, 1 / scale, True)
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\data\util.py", line 351, in imresize_np
    in_H, in_W, in_C = img.size()
ValueError: not enough values to unpack (expected 3, got 2)

FULL LOG:
[train_190114-004852.log](https://github.com/xinntao/BasicSR/files/2754110/train_190114-004852.log)

**Comment by xinntao** [comment]
Hi @Ifinxx,
From `File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\data\util.py", line 351, in imresize_np in_H, in_W, in_C = img.size() ValueError: not enough values to unpack (expected 3, got 2)`
You used gray images? 

BTW, I have seen that you have a pair of {HR, LR} images during training, but it ran into Line 90-94 in the `LRHR_dataset.py` file, 
https://github.com/xinntao/BasicSR/blob/4f3889667b5bcab16711c69d75db9754945ff212/codes/data/LRHR_dataset.py#L90-L94

, which means you have some training data smaller than training patch size (HR_size=128 in your log).
Recommend to inspect your training data. Because `util.imresize_np` is used for MATLAB bicubic kernel, maybe not the same as the degradation kernels from your data.

**Comment by Ifinxx** [comment]
I used imagemagick to turn these into 128x128 tiles, in doing so I forgot to remove tiles that were left over from the conversion and had some smaller tiles left over (I need to learn a batch removal command with imagemagick to remove if less than 128x128). So I manually removed these smaller tiles and reran the test, I then got a 3 and 1 dimension error so I checked to see if there were issues regarding grayscale like you mentioned. Strangely it appears imagemagick converted the png format incorrectly so I ran `mogrify -define png:format=png24 -type TrueColor *.png` and batch fixed the format issue. It appears to be working now, no errors so far just running slowly. Thank you for the help!

**Comment by Ifinxx** [comment]
@xinntao Sorry for so many questions. It appears now I get a new error when training.

Traceback (most recent call last):
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\train.py", line 173, in <module>
    main()
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\train.py", line 148, in main
    avg_psnr += util.calculate_psnr(cropped_sr_img * 255, cropped_gt_img * 255)
  File "C:\Users\ToddS\Desktop\TRAINING AI\BasicSR-master\codes\utils\util.py", line 111, in calculate_psnr
    mse = np.mean((img1 - img2)**2)
ValueError: operands could not be broadcast together with shapes (120,52,3) (120,48,3)

What should I do / look into to resolve this issue? 

Complete log here: 
[train_190114-023232.log](https://github.com/xinntao/BasicSR/files/2756743/train_190114-023232.log)

**Comment by stonessss** [comment]
@Ifinxx Hello, I encountered the same problem while training BasicSR. How did you solve it ?
