### ISSUE TITLE
Can't create lmdb

### ISSUE THREAD

**Issue by Ichigo14** [xinntao/BasicSR#87]
Sorry i'm new for this. I have this error.

`Read images...
[                                                  ] 0/2653, elapsed: 0s, ETA:
Start...
Traceback (most recent call last):
  File "create_lmdb.py", line 22, in <module>
    pbar.update('Read {}'.format(v))
  File "C:\ESRGAN-master\BasicSR-master\codes\utils\progress_bar.py", line 40, in update
    fps = self.completed / elapsed
ZeroDivisionError: float division by zero`

**Comment by xinntao** [comment]
The error means the elapsed time is zero. May check the configurations.
You can also comment on the progress_bar lines, which only for printing some info.
